Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'auth/login', to: 'authentication#login'
      post 'auth/register', to: 'authentication#register'
      delete 'auth/logout', to: 'authentication#logout'
      
      resources :users
      resources :reservations
      resources :cars
    end
  end
end

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy, foreign_key: 'car_id', class_name: 'Reservation'

  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true, numericality: { less_than_or_equal_to: Date.today.year }
  validates :daily_rate, presence: true, numericality: { greater_than: 0 }
  validates :user, presence: true
  validates :image, presence: true
  validates :description, presence: true
end

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  before_action :authenticate_request

  # GET /cars or /cars.json
  def index
    @cars = Car.all
    render json: @cars
  end

  # GET /cars/1 or /cars/1.json
  def show
    render json: @car
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit; end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = @current_user.id

    if @car.save
      render json: { car: @car, message: 'Car added successfully!' }, status: :created
    else
      render json: { message: @car.errors.full_messages.join(', ') }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json

  def destroy
    @car = Car.find(params[:id])
    if @car.destroy
      render json: { message: 'Car successfully deleted' }, status: :ok
    else
      render json: { message: @car.errors.full_messages.join(', ') }, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:make, :model, :year, :image, :description, :daily_rate)
  end
end

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/helpers/cars_helper.rb
module CarsHelper
end

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Make:</strong>
    <%= car.make %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= car.year %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= car.price %>
  </p>

</div>

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :make, style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

Documents/microverse/module 6/FINAL CAPSTONE/Appointment-Capstone-Backend/app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>